### ISSUE TITLE
provide "fat" PHAR of the SDK for standalone scripts

### ISSUE THREAD

**Issue by nkuehn** [commercetools/commercetools-php-sdk#149]
Import / Export System integrations are often simple PHP scripts that are triggered by cron. 

It seems that system administrators are reluctant to install composer and "install" the SDK via composer (the wording "install" seems to scare off, among other aspects like composer installation on windows being unintuitive). 

For these cases it would be helpful to provide a PHAR file for manual download that contains an autoloader, the SDK plus all transient runtime dependencies.  

Then a system admin would just have to put the script(s) next to the PHAR and run the script. 

``` php
<?php
include 'commercetools-php-sdk-1.0.1.phar';
?>
```

**Comment by CHH** [comment]
:+1:

**Comment by nkuehn** [comment]
something like this might help:  https://github.com/clue/phar-composer

**Comment by b3nl** [comment]
+1

**Comment by jayS-de** [comment]
I added a phar of the SDK to the 1.6 release. This phar includes the minimum requirements.

An example how this could be used:

```php
<?php

require __DIR__ . '/commercetools-php-sdk.phar';

$config = \Commercetools\Core\Config::fromArray(['client_id' => 'myClientId', 'client_secret' => 'myClientSecret', 'project' => 'myProjectId']);
$client = \Commercetools\Core\Client::ofConfig($config);


$request = \Commercetools\Core\Request\Project\ProjectGetRequest::of();

$response = $client->execute($request);

$project = $request->mapFromResponse($response);

var_dump($project->toArray());
```

In the main folder of the phar resides an index.php which bootstraps the internal vendor/autoload.php. Have fun trying it out. In a future release I will provide some infos on the usage in the README.
