### ISSUE TITLE
(phpcs) too long use statements

### ISSUE THREAD

**Issue by emtii** [commercetools/commercetools-php-sdk#232]
// FEEDBACK 

e.g.
use Commercetools\Core\Request\Products\Command\ProductSetAttributeInAllVariantsAction;

Is more than 85 signs and more than 120 signs, our builds internally work with php cs default config and we would like to be able to rely on this setting, but are forced to put off this check for the moment.

In general it would make a lot of sense to provide use statements not longer than 120 or 85 signs.

**Comment by jayS-de** [comment]
Which coding standard are you using or are you running phpcs just without any parameters? E.G. using the ```phpcs --standard=PSR2``` could already help, as PSR2 defines a soft limit for line length (see [PSR-2](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#23-lines))

Another possibility is to ignore violating parts (see [phpcs documentation](https://pear.php.net/manual/en/package.php.php-codesniffer.advanced-usage.php)) with ```@codingStandardsIgnoreStart``` or ```@codingStandardsIgnoreLine``` annotations.

**Comment by emtii** [comment]
We added ignore annotations :) can get closed. Thx!
