### ISSUE TITLE
Do not catch non recoverable exceptions

### ISSUE THREAD

**Issue by Haehnchen** [commercetools/commercetools-php-sdk#253]
We had some problems on API stability last days. It looks like all client exceptions of guzzle are catched and running into `isError` condition which results in empty models instead i would suggest to throw an non recoverable exception.
We ran into load balancer and invalid project responses.

**Comment by jayS-de** [comment]
It's possible to set the throwExceptions-Flag in the config object of the client will switch the behavior from catching to throwing all exceptions. As you might be using the symfony bundle I will open an issue there.
