### ISSUE TITLE
Add range filter implementations

### ISSUE THREAD

**Issue by Haehnchen** [commercetools/commercetools-php-sdk#265]
Currently is looks like there is no way to define a filter with range conditions. because range is wrapped by double quotes. Instead of using `setName` method as a workaround it  would be nice to allow using `setValue` which also allow array values

workaround:
```
$filter->setName(sprintf(
  '%s:range(%s to %s)',
  $filter->getName(),
  $values[$facetName]['min'],
  $values[$facetName]['max']
));
```

**Comment by jayS-de** [comment]
There is the Commercetools\Core\Model\Product\Search\FilterRangeCollection already which solves your issue. Please see also Commercetools\Core\Model\Product\Search\FilterTest::testRange and Commercetools\Core\Model\Product\Search\FilterRangeTest for possible uses.
