### ISSUE TITLE
Reduce log-level for every Request

### ISSUE THREAD

**Issue by b3nl** [commercetools/commercetools-php-sdk#300]
It seems that you log every request with the "info"-level but i think, for a real application, this should be reduced to "debug". A real application uses this information only for debugging and not as "**Interesting events.** (https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md).

**Comment by jayS-de** [comment]
The LogLevel::INFO is the default value from Guzzle. I think it's a useful information to log every outgoing connection. You could also configure the logger to log everything with Notice level as minimum. Besides that we will introduce a configuration option for the SDK client to specify the LogLevel.

**Comment by b3nl** [comment]
+1 thanks
