### ISSUE TITLE
Parameter value not added in query of ProductsSuggestRequest 

### ISSUE THREAD

**Issue by Haehnchen** [commercetools/commercetools-php-sdk#310]
https://github.com/commercetools/commercetools-php-sdk/blob/develop/src/Request/Products/ProductsSuggestRequest.php#L149

```
$params = array_merge($params, array_keys($this->params));
```

eg FOOBAR=true is not setted because just the key is used. also think of use `http_build_query` which provides besser query and urlencoding

**Comment by jayS-de** [comment]
http_build_query would not be working as most of the parameters can be used multiple times. Will take a look at the ProductSuggestRequest and the PR about this.
