### ISSUE TITLE
StateReference::ofKey() creates invalid reference

### ISSUE THREAD

**Issue by jhofm** [commercetools/commercetools-php-sdk#311]
When creating a reference to a state by using the StateReference::ofKey() factory method, the resulting JSON 
``` 
"state": {
    "typeId": "state",
    "key": "foo"
  } 
``` 
can not be used in a ProductCreateRequest because the product/create API expects the reference to contain an id ("detailedErrorMessage": "state -> id: Missing required value")

I'm currently a bit pressed for time, so i haven't tested if other API endpoints accept such a state reference, meaning i'm unsure if this is is a problem with the article API or the SDK. Wanted to give a heads up anyway.

**Comment by jayS-de** [comment]
The ofKey constructor actually creates a ResourceIdentifier, but the Product TransitionState action awaits a Reference, so you have to use the ofId constructor.

Besides that it's not that easy to differentiate between both types in the SDK, but maybe I will find some solution so I will leave this ticket open.

**Comment by jenschude** [comment]
Using ResourceIdentifiers for state transitions is supported by the API so this issue has been solved by the API
