### ISSUE TITLE
Optimize PriceFinder iterator filter

### ISSUE THREAD

**Issue by Haehnchen** [commercetools/commercetools-php-sdk#318]
Instead of iterator over all Prices just exit on first match.

```php
# vendor/commercetools/php-sdk/commons/Helper/PriceFinder.php
#\Commercetools\Commons\Helper\PriceFinder::findPrice

$prices = new \CallbackFilterIterator(...);

foreach ($prices as $price) {
    return $price;
}

return null;
```

**Comment by jayS-de** [comment]
Thats exactly what happens.

The first match found by the CallbackFilterIterator is returned by the function.

Btw I would discourage you to use the PriceFinder. Better use the [price selection](http://dev.commercetools.com/http-api-projects-products.html#price-selection) functionality which gives you the price that the platform would select if this product is put into a cart.

E.G.:
```
ProductProjectionSearchRequest::of()->currency('EUR')->country('DE') 
```
