### ISSUE TITLE
Update Product by ID Request

### ISSUE THREAD

**Issue by DenisMir** [commercetools/commercetools-php-sdk#319]
Does the PHP SDK lack a "[Update Product by ID](http://dev.commercetools.com/http-api-projects-products.html#update-product-by-id)" request object? I'm not able to find one. Or is there a reason that there is only a `ProductUpdateByKeyRequest` object?

**Comment by jayS-de** [comment]
Updates byID done using the ProductUpdateRequest.

The reason for this is, that the naming scheme evolved a little bit over time as the by key functionality was introduced after the SDKs api was quite stable and in use.

**Comment by DenisMir** [comment]
Thank you very much @jayS-de .
