### ISSUE TITLE
Add LineItem + externalPrice

### ISSUE THREAD

**Issue by nicolaaretini** [commercetools/commercetools-php-sdk#320]
I see in the docs you updated the addlineitem action:
http://dev.commercetools.com/http-api-projects-carts.html#add-lineitem
With optional fields externalprice, externalTotalPrice:
 
Are you planning to update the SDK in order to have a new call with these optional fields?
Thanks

**Comment by jayS-de** [comment]
Just created the relevant issues to keep up with the API features. See #322
