### ISSUE TITLE
HTTP 400 error does not handle multiple errors properly.

### ISSUE THREAD

**Issue by kortwotze** [commercetools/commercetools-php-sdk#385]
This one is pretty simple: 
If I submit an OrderQueryRequest with a where()-Predicate that contains more than one error, there is only one error-message returned that includes all present errors concatenated.

Request:
`$orderRequest = OrderQueryRequest::of()->where('orderState="aOpen" and limit=5');`

Response:

```
Array
(
    [statusCode] => 400
    [message] => Malformed parameter: where: Invalid enum value for OrderState: aOpenThe field 'limit' does not exist.
    [errors] => Array
        (
            [0] => Array
                (
                    [code] => InvalidInput
                    [message] => Malformed parameter: where: Invalid enum value for OrderState: aOpenThe field 'limit' does not exist.
                )

        )

)
```

I am nor sure if it is intended this way or if I am doing anything wrong.

**Comment by jenschude** [comment]
Actually this is not directly an SDK issue as the message comes from the API. Could you please open an support issue for this at https://support.commercetools.com/

**Comment by jenschude** [comment]
I will then track the support ticket and leave this issue open till it is resolved

**Comment by kortwotze** [comment]
Right, will do. Sorry for the hard delay - I had the flu and was incapable of doing anything. :(

**Comment by jenschude** [comment]
Issue has been resolved
