### ISSUE TITLE
More than one sort-parameter are supported by API but not by SDK

### ISSUE THREAD

**Issue by ep-dka** [commercetools/commercetools-php-sdk#386]
```
$search = InventoryQueryRequest::of();
$search->sort('masterData.staged.masterVariant.sku')->sort('id asc');
```
should produce a query with "..&sort=..sku&sort=id%20asc" and not "id asc" in the first place.
AFAICS the reason is that AbstractApiRequest::convertToString sorts the parameters before placing the request. 

I tried to produce a small PR, but failed because the parameters are stored intentionally this way and my changes broke some test-cases.

We would like to iterate over whole bunches of products and inventories and do so in a streaming (and over sku-synchronized) fashion, which isn't possible ATM.

Viele Grüße // David

**Comment by jenschude** [comment]
You are right. The sorting is the issue. This was done for canonical URIs but the sort is here problematic. Will fix this and also add it to the next release. If necessary I could also fix it afterwards for previous versions
