### ISSUE TITLE
OrderQueryRequest - mapFromResponse does not cover all fields from API response

### ISSUE THREAD

**Issue by kortwotze** [commercetools/commercetools-php-sdk#394]
This is a simple one: The origin field that commercetools delivers from an OrderQueryRequest is not mapped to the Order Object. In fact, the Order Object does not even have that field.

Maybe I am missing even more fields, but the "origin" field made this pop up to me.

**Comment by jenschude** [comment]
The origin field has been added with the version 2.3 to the SDK

**Comment by kortwotze** [comment]
Misstake in composer.json - a wrong version constraint kept me from anything > 1.9. I am sorry to have bothered you :(

**Comment by jenschude** [comment]
Happened to me also once.

You're welcome :sweat_smile:
