### ISSUE TITLE
HTTP-ClientOption verify=>true wont arrive at Guzzle-Client in the most recent version.

### ISSUE THREAD

**Issue by rkrx** [commercetools/commercetools-php-sdk#395]
I have the following (local) setup:

```php
$configParams = [
	'client_id' => ...,
	'client_secret' => ...,
	'project' => ...,
	'clientOptions' => ['verify' => false]
];
...
$config = Commercetools\Core\Config::fromArray($configParams)->setContext($context);
...
```

It seems [`Commercetools\Core\Client\OAuth\Manager`](https://github.com/commercetools/commercetools-php-sdk/blob/53aaa0e1dbd6c7016fc59acf0f264e811f08eb17/src/Core/Client/OAuth/Manager.php#L254) and [`Commercetools\Core\Client`](https://github.com/commercetools/commercetools-php-sdk/blob/53aaa0e1dbd6c7016fc59acf0f264e811f08eb17/src/Core/Client.php#L209) create distinct instances of `Guzzle\Client`, but only  `Commercetools\Core\Client` passes `'verify' => false` to it's Guzzle-Instance.

**Comment by jenschude** [comment]
Could verify this and will create a fix for this. As a workaround for now to instantiate a guzzle http client with the verify option set you could do this:

```php
$client = Client::of($config);
$client->getOauthManager()->getHttpClient(['verify' => false]);
```

**Comment by jenschude** [comment]
In the next release the HTTP client of the OAuth manager can be configured with oauthClientOptions

I had to separate them as you can also manipulate the handler stack using the client options.

**Comment by rkrx** [comment]
I would suggest to replace all that overcomplicated logic with a Builder and use DI (only constructor-injection) everywhere instead of this outdated `*Aware`-stuff. 
I'd expect a remarkable reduction in LOC and complexity, which I would really welcome here 😃
