### ISSUE TITLE
fractionDigits in Money should be of type int

### ISSUE THREAD

**Issue by mchainanicimpress** [commercetools/commercetools-php-sdk#429]
fractionDigits in the HighPrecisionMoney and CentPrecisionMoney models expect type string but the definition in api documentation requires it to be a number. Because of this the model is rendered unusable.

**Comment by jenschude** [comment]
Oh man. Copy&Paste error. I made a hotfix and will release the version 2.5.1 which fixes this.

For the future I will take a look how I could prevent some of these silly mistakes using our RAML spec.

**Comment by mchainanicimpress** [comment]
👍
