### ISSUE TITLE
Master Data Current exists even if the product is unpublished

### ISSUE THREAD

**Issue by sadokmtir** [commercetools/commercetools-php-sdk#475]
So the problem is that when I create a . draft product with a draft variant and then make it unpublished and pushed it, later on when I try to retrieve it I can see that my product has the draft variant on the staged attribute and on the current as well which should not happen normally.

This is my code to create a draft product:

```
private function getDraft(string $name): ProductDraft
    {
        $draft = ProductDraft::ofTypeNameAndSlug(
            ProductTypeReference::ofKey('whatever'),
            LocalizedString::ofLangAndText('en', $name),
            LocalizedString::ofLangAndText('en', TextHelper::slugify($this->productKey.'-'.$name))
        );

        return $draft;
    }
```

```
variantDraft = ProductVariantDraft::of()
            ->setSku('XX')
            ->setKey('XX');

        $draft = $this->getDraft($productName)
        ->setKey($this->productKey)
        ->setMasterVariant($variantDraft)
        ->setPublish(false);
        $request  = ProductCreateRequest::ofDraft($draft);
        $response = $this->client->execute($request);

        $this->product = $request->mapResponse($response);
```

 
And this is how I get the product:

  ```
$request  = ProductByKeyGetRequest::ofKey($this->productKey);
        $response = $this->client->execute($request);

        $this->product = $request->mapResponse($response);

```

**Comment by jenschude** [comment]
This is how the API responds to a newly created product. Cause after creation the draft is the current state of the product. But the published flag is set to false. You could use the product projections which only return either the current published product projection. Or the staged one. If not published the current projection will return a 404 not found.
