### ISSUE TITLE
Chain of promises does not work.

### ISSUE THREAD

**Issue by GDXbsv** [commercetools/commercetools-php-sdk#476]
I can not use promises chaining, see an example.
```
        $this->client->executeAsync($request)->then(
            function (ResponseInterface $response): ApiResponseInterface {
                return $this->client->executeAsync($request);
            }
        )->wait();
```
So the second `return $this->client->executeAsync($request);` will be never resolved.

Problem connected with different interfaces in sdk and guzzle: 
```
\GuzzleHttp\Promise\Promise::wait
```
```
$inner = $this->result instanceof PromiseInterface
            ? $this->result->wait($unwrap)
            : $this->result;
```
SDK does not follow PromiseInterface.

**Comment by GDXbsv** [comment]
In the same time because of interfaces it is not possible to use guzzle functions like 'all' 'same' 'coroutine'. I didn't find any similar methods in sdk.
And it some problems with 'queue()->run()' (I am not sure yet while can not really create and manage promises)

**Comment by jenschude** [comment]
For the chaining problem please take a look at issue #274. About the other functions I would have to take a closer look tomorrow

**Comment by jenschude** [comment]
I see the issue with the promise functions. My suggestion would be to add a function to expose the wrapped promises. This would be a short term task which I can release in the next week.

Also I believe that a client factory which returns a preconfigured guzzle client may serve the needs for asynchronous tasks better than a wrapped http client. This would take a little more effort but should also not take that much time.

**Comment by jenschude** [comment]
With the [v2.8.0](https://github.com/commercetools/commercetools-php-sdk/releases/tag/v2.8.0) release it's now possible to extract the guzzle promise as well to create a preconfigured guzzle client. See the [README](https://github.com/commercetools/commercetools-php-sdk#using-the-client-factory) for some details.
