### ISSUE TITLE
Fix for executeAsync

### ISSUE THREAD

**Issue by GDXbsv** [commercetools/commercetools-php-sdk#480]
I had to make some fixes in the `\Commercetools\Core\Client::executeAsync`

```php
class CommerceToolsClientFix extends Client
{
    public function executeAsync(ClientRequestInterface $request, array $headers = null, array $clientOptions = [])
    {
        if ($request instanceof ContextAwareInterface) {
            $request->setContextIfNull($this->getConfig()->getContext());
        }
        $client      = $this->getHttpClient($clientOptions);
        $httpRequest = $this->createHttpRequest($request, $headers);
        if ($client instanceof AdapterOptionInterface) {
            /**
             * @psalm-suppress InternalMethod
             * @psalm-suppress TooManyArguments
             * @psalm-suppress UndefinedInterfaceMethod
             */
            $response = $request->buildResponse($client->executeAsync($httpRequest, $this->httpClient->getConfig(null)));
        } else {
            /** @psalm-suppress InternalMethod */
            $response = $request->buildResponse($client->executeAsync($httpRequest));
        }

        $response = $response->then(

            function (ResponseInterface $httpResponse) use ($httpRequest): ResponseInterface {
                $this->logDeprecatedRequest($httpResponse, $httpRequest);

                return $httpResponse;
            }
        );

        return $response;
    }
}
```
I wanted to use 
```php
        $stack = HandlerStack::create(new FooHandler());

        $response = $this->client->executeAsync(
            $request,
            null,
            [
                'handler' => $stack,
            ]
        );
```
Problems:
1. Do not pass `$clientOptions` in the `$client = $this->getHttpClient();` 
2. The  order. `createHttpRequest` uses a client  which can not be created with options, so we have to start $this->getHttpClient() at first.
```
        $httpRequest = $this->createHttpRequest($request, $headers);
        $client = $this->getHttpClient();
```
3. After the first call '$client->executeAsync($httpRequest, $clientOptions)' does not receive the ComerceTools handlers. Because you set it only once and after that it will be a new object in the  $clientOptions without your GuzzleMiddlewares. 

4. You send authenticate request synchronously. `\Commercetools\Core\Client\Adapter\Guzzle6Adapter::authenticate`, It is not what I am expecting for the asynchronous call.
Could you add a way to do it asynchronously.

**Comment by jenschude** [comment]
Is it really necessary to inject for every call the handler stack? The client options in the execute methods are meant to be used for additional headers, custom timeouts etc.

If the stack should be only injected once this could also be achieved by pre-initialize the wrapped HTTP client with the custom stack. This avoids also to merge client options for every request again.

```php
$stack = HandlerStack::create(new FooHandler());
$client->getHttpClient('handler' => $stack);

$client->executeAsync($request)
```

If you want to just inject an additional middleware you could also use this snippet, which will push the handler to the handler stack:

```php
$client->getHttpClient()->addHandler(Middleware::mapRequest(function (RequestInterface $request) { return $request; })
```

Besides that I see the point with the authentication provider to use a synchronous call. I could try to change this also to a promise but as the result is cached the blocking call will only happen on the first API request. All following will use a cached token.

**Comment by GDXbsv** [comment]
Thanks. I have changed my code by your recommendation and it is working.

But setting the client options through the getter is confusing. I would suggest to do it by the configuration. For example how Amazon does it.
```
        $options = [
            'http_handler' => HandlerStack::create(new FooHandler()),
            'region'          => $awsSqsRegion,
            'version'         => $awsSqsVersion,
            'retries'          => 0
        ];
``` 

It would be useful for  http://docs.guzzlephp.org/en/stable/testing.html#mock-handler or `amphp` or `ReactPHP` handler.

**Comment by jenschude** [comment]
Yeah I edited my comment with a section how to do so in the configuration. Maybe you missed this part.

```php
$stack = HandlerStack::create(new FooHandler());
$client = Client::ofConfig(Config::fromArray([])->setClientOptions(['handler' => $stack]));
```

**Comment by jenschude** [comment]
Please see also https://github.com/commercetools/commercetools-php-sdk/issues/476#issuecomment-499428196
