### ISSUE TITLE
Setting attributes marked as SameForAll needs to be added each time

### ISSUE THREAD

**Issue by sadokmtir** [commercetools/commercetools-php-sdk#490]
As we are creating a product with some attributes marked as **same for all**, when we try to add a variant to product, we get 400 status code _InvalidField_ with message       

> "message"      : "Using no value is not valid for field 'fieldName'. The allowed value is '\"fieldValue.\"'. The value of the attribute must be the same across all variants.",

If these attributes are same for all, why we have to set them each time when we add a variant. Is it kind of limitation or I am missing something ?

**Comment by jenschude** [comment]
This is an issue arising from the constraint validation by the API, which validates the constraints on setting the attribute.
