### ISSUE TITLE
getTaxedPrice() function of Commercetools\Core\Model\Cart\Cart does not seems to be working

### ISSUE THREAD

**Issue by raju-cimpress** [commercetools/commercetools-php-sdk#502]
I am fetching cart using CartByIdGetRequest.

        $request = CartByIdGetRequest::ofId($id);
        $response = Client::execute($request);
        $cart = $request->mapResponse($response);

Above $cart is Commercetools\Core\Model\Cart\Cart object.

when I see `$cart->toArray()`, it has value for taxedPrice.
```      "taxedPrice" => array:2 [
        "totalNet" => array:4 [
          "type" => "centPrecision"
          "currencyCode" => "EUR"
          "centAmount" => 5350
          "fractionDigits" => 2
        ]
        "totalGross" => array:4 [
          "type" => "centPrecision"
          "currencyCode" => "EUR"
          "centAmount" => 6527
          "fractionDigits" => 2
        ]
      ]
```
However calling `$cart->getTaxedPrice()` returns null value.

I using 2.8 version of the SDK

**Comment by jenschude** [comment]
I could not reproduce your problem. I used the following code snippet

```php
   public function testCreateTaxedPrice()
    {
        $draft = CartDraft::ofCurrency('EUR')
            ->setCountry('DE')
            ->setShippingAddress(Address::of()->setCountry('DE'));

        $request = CartCreateRequest::ofDraft($draft);
        $response = $request->executeWithClient($this->getClient());
        $cart = $request->mapResponse($response);

        $this->assertSame($draft->getCurrency(), $cart->getTotalPrice()->getCurrencyCode());
        $this->assertSame($draft->getCountry(), $cart->getCountry());
        $this->assertSame(0, $cart->getTotalPrice()->getCentAmount());
        $this->assertSame(0, $cart->getTaxedPrice()->getTotalNet()->getCentAmount());
    }
```

Typically the cart doesn't has a TaxedPrice when there is no shipping address set.

If you still have the problem, please add the json payload to this issue. You could read the pure json with this snippet:

```php
$json = (string)$response->getBody();
```

**Comment by raju-cimpress** [comment]
Thanks for this information. Yes, shipping address was indeed missing and it worked after adding the shipping address.
I raised the issue because, postman call to the api was returning taxedPrice but SDK function was not returning it.
