### ISSUE TITLE
Provide and document a way to escape query parameters

### ISSUE THREAD

**Issue by phihag** [commercetools/commercetools-php-sdk#505]
How do am I supposed to escape attacker-controlled values in a where query?

For example, I have a query like
```
CartDiscountQueryRequest::of()->where('name(de-DE="' . $name . '")');
```

In some cases, I do control `$name`, but in some requests it is user-provided, or even something like `$_GET['name']`. Sometimes it is harmless if a potential attacker can chose the query, but in other cases this is not desired.

In [the documentation](https://commercetools.github.io/commercetools-php-sdk/docs/master/source-class-Commercetools.Core.Request.QueryRequestInterface.html#10-14), I 
 was not able to find a way analogous to [prepared statements](https://www.php.net/manual/en/pdo.prepared-statements.php), e.g. something lik
```
CartDiscountQueryRequest::of()->where('name(de-DE=:name)', array(':name' =>  $name));
CartDiscountQueryRequest::of()->where('name(de-DE=?)', array($name));
```

Even if there is no way for binding parameters, surely there must be a function to escape user-provided values, like [PDO::quote](https://www.php.net/manual/en/pdo.quote.php). This function should be documented, so that it is google-able with `commercetools php query escape` or similar.

**Comment by jenschude** [comment]
Hi,

actually there are different ways and it depends on your use case. The main issue for parametrized strings is that someone could escape the double quotes. So the solution is to escape/sanitize the double quotes in any parameter which are not under your control. The choice is up to you and as already said depends also on the use case, e.g.  a resource could hold a value with double quotes and how it has been stored.

Some possibilities:

```php
// escape double quotes
CartDiscountQueryRequest::of()->where('name(de-DE="' . addslashes($name) . '")');
CartDiscountQueryRequest::of()->where('name(de-DE="' . str_replace('"', '\"', $name) . '")');

// just remove double quotes
CartDiscountQueryRequest::of()->where('name(de-DE="' . str_replace('"', '', $name) . '")');

// render special characters to safe replacements
CartDiscountQueryRequest::of()->where('name(de-DE="' . htmlentities($name) . '")');
```

But this only takes into account string values. For numbers or booleans this may not be sufficient, here are some possible mitigations:

```php
$customerId = 'abcdef-12345';
$version = $_GET['version'];

// check correct type
if (!is_numeric($version)) {
    $version = (int)$version; // case to sane type
    $version = 1; // set sane default
		throw new InvalidArgumentException('throw meaningful message');
}

// cast to a sane type
OrderQueryRequest::of()->where('customerId = "' . $customerId . '" and version >= ' . (int)$version);

// change the precedence of the operators
OrderQueryRequest::of()->where('customerId = "' . $customerId . '")->where(version >= ' . $version); // split the conditions to different where parameters
OrderQueryRequest::of()->where('customerId = "' . $customerId . '" and (version >= ' . $version . ')'); // forced operator precedence

// best combine both
OrderQueryRequest::of()->where('customerId = "' . $customerId . '")->where(version >= ' . (int)$version);
```


And you could also write a small function to prepare a where with parameters as like as prepared statements are doing it:

```php

$where = prepareWhere('customerEmail=":email"', ['email' => $_GET['email']]);
/**
 * @param string $where
 * @param array $parameters
 * @return string
 */
public function prepareWhere($where, array $parameters)
{
    $where = str_replace(
        array_map(
            function ($value) {
                return ":$value";
            },
            array_keys($parameters)
        ),
        array_map(
            function ($value) {
                return str_replace('"', '\"', $value);
            },
            array_values($parameters)
        ),
        $where
    );
    return $where;
}
```

We will take a look what kind of options we may already provide as helpers inside the SDK itself, in the mean time I hope this helps.

**Comment by phihag** [comment]
@jenschude Thank you very much for providing a wealth of options!
I would strongly prefer these options to be built in, so there is one obviously correct way of doing things, and no chance to mess up.

For example, `str_replace` does **not** work, as it results in the input `\" or x` as being encoded as `\\" or x`

**Comment by jenschude** [comment]
Yes but as it's not escaping the double quotes the query itself may be invalid, but as least you are not leaking information

**Comment by jenschude** [comment]
@phihag I just found out, that the API already supports input parameters in predicates. Also it's maybe hard to find. See [predicate spec docs](https://docs.commercetools.com/query-specs/query-predicate-spec.html#sec-Comparison)

For example:

```php
$request = ProductQueryRequest::of()->where('masterData(current(name(en=:name)))');
$request->addParam("name", $draft->getName()->en);
```

This will correctly put in the value of name in the predicate without the need to escape or enclose a parameter in double quotes.

I may think about adding the parameters as an optional argument to the where in the future. But this already works.
