### ISSUE TITLE
Add customer store actions to SDK

### ISSUE THREAD

**Issue by raju-cimpress** [commercetools/commercetools-php-sdk#534]
As per the commercetools documentation, api now support setting setting, adding and removing stores for the customer. However seems php-sdk does not have classes for these actions.

https://docs.commercetools.com/http-api-projects-customers#set-stores-beta
https://docs.commercetools.com/http-api-projects-customers#add-store-beta
https://docs.commercetools.com/http-api-projects-customers#remove-store-beta

Can SDK be updated for the above requests?

**Comment by jenschude** [comment]
Hi sorry for the late answer.

Yes they will be added soon.

**Comment by barbara79** [comment]
Closed by #538
