### ISSUE TITLE
No value for locale set

### ISSUE THREAD

**Issue by migo315** [commercetools/commercetools-php-sdk#539]
I always get the message "No value for locale set" even though I have set it.
You use `\Locale::canonicalize()` in LocalizedString to prepare the locale.
See https://github.com/commercetools/commercetools-php-sdk/blob/develop/src/Core/Model/Common/LocalizedString.php#L68

If I run `echo \Locale::canonicalize('de-de');` I will get `de_DE`. But CommerceTools returns `de-DE` in ProductProjection responses. That means, that I never get a matched locale when my locale has more than two chars.

**Comment by jenschude** [comment]
Could you give me a snippet what you are trying to achieve and where you have the Locale from? Btw at https://github.com/commercetools/commercetools-php-sdk/blob/dc6836a7ad051a79a9cc03cae1668bccd8c24026/src/Core/Model/Common/LocalizedString.php#L134 the underscore is replaced with a hyphen before serializing to the API. So it should be safe to use the PHP locale format.

**Comment by migo315** [comment]
Forget it. Found my error. Everything fine ;-)
