### ISSUE TITLE
How to assert existence of Type field?

### ISSUE THREAD

**Issue by advancingu** [commercetools/commercetools-php-sdk#589]
What is the correct way to assert that a custom Type has a specific field defined and available to use?

I've been trying to run code such as the one below, however the result is always `false`:
```php
$order->getCustom()->hasField($myField);
```

**Comment by jenschude** [comment]
$order->getCustom()->getFields()->hasField($myField);

**Comment by jenschude** [comment]
The structure of a custom field looks like

```
{
  [...]
  "custom": {
    "type": {
      "key": "my-category"
    },
    "fields": {
      "description": "example description"
    }
  }
}
```

So it would have to be: `$order->getCustom()->getFields()->hasField($myField);`

**Comment by advancingu** [comment]
I had tried that already and that also only returned `false`.

What is interesting is that there is a mismatch between what the order holds and what the type definition says.

Order:
```json
{
    "type": "Order",
    // ...
    "custom": {
        "type": {
            "typeId": "type",
            "id": "dca5267a-096b-49d5-8371-b340a54cccf9"
        },
        "fields": {}
    },
    // ...
}
```

Type:
```json
{
    "id": "dca5267a-096b-49d5-8371-b340a54cccf9",
    // ...
    "resourceTypeIds": [
        "order"
    ],
    "fieldDefinitions": [
        {
            "name": "myType",
            "label": {
                // ...
            },
            "required": false,
            "type": {
                "name": "String"
            },
            "inputHint": "SingleLine"
        },
        // ...
    ]
}
```

It appears like it is not sufficient to apply a custom type to an order with the following command and all the fields have to be applied individually as well?
```php
OrderUpdateRequest::ofIdAndVersion($order->getId(), $order->getVersion())
    ->addAction(OrderSetCustomTypeAction::of()->setType($desiredType->getReference()))
```

**Comment by jenschude** [comment]
The custom field only holds the actual data and hasField only checks if some field is set.

Either you know which field is configured based on the type. Or you would have to expand the type and read the information from the referenced object

```
$request->expand('custom.type');

$order->getCustom()->getType()->getObj()->getFieldDefinitions()->getByName($fieldName);
```

**Comment by advancingu** [comment]
Adding `expand('custom.type')` to the original resource query did the trick. The custom type is then populated and I can run the verification. Thanks for the quick replies!

**Comment by jenschude** [comment]
But please be aware that reference expansion comes with a cost. If you have to do this with a lot of requests I would fetch all types, cache them and look them up from the cache.

**Comment by advancingu** [comment]
Of course. The code will be refactored when it becomes an issue. For now `expand` is an acceptable solution.
