### ISSUE TITLE
Guzzle 6 adapter autodetection bugged

### ISSUE THREAD

**Issue by arudolph-cxt** [commercetools/commercetools-php-sdk#596]
This bug was discovered with the commercetools php-sdk version 2.9.0 but is also present in the newest 2.12.0
https://github.com/commercetools/commercetools-php-sdk/blob/develop/src/Core/Client/Adapter/AdapterFactory.php#L41-L48

If a project has guzzle 6 (6.5.5 to be precise) installed, the autodetection inside the AdapterFactory tries to automatically determine if it should use guzzle6 or guzzle5 and falsely decides for guzzle5

This code example should illustrate the issue:
```php
    public function getClass($name = null)
    {
        var_dump(ClientInterface::VERSION); // "6.5.5"
        var_dump(defined('\GuzzleHttp\ClientInterface::MAJOR_VERSION')); // false
        var_dump(Client::VERSION); // "6.5.5"
        var_dump(version_compare(Client::class . '::VERSION', '6.0.0', '>=')); // false

        if (is_null($name)) {
            if (defined('\GuzzleHttp\ClientInterface::MAJOR_VERSION')) {
                $name = 'guzzle6';
            } elseif (version_compare(Client::class . '::VERSION', '6.0.0', '>=')) {
                $name = 'guzzle6';
            } else {
                $name = 'guzzle5';
            }
        }
        if (isset($this->adapters[$name])) {
            return $this->adapters[$name];
        }

        throw new InvalidArgumentException();
    }
```
The two conditions to detect guzzle6 arent met, altough guzzle 6 is installed and guzzle 5 is not present.

**Comment by jenschude** [comment]
Quick workaround would be to set in the config object the adapter to 'guzzle6'.

But will take a look into it later and most likely change the order so that it defaults to guzzle 6/7 and only uses 5 if it's really below 6.

**Comment by jenschude** [comment]
Just released https://github.com/commercetools/commercetools-php-sdk/releases/tag/v2.12.1

This should fix the issue
