### ISSUE TITLE
Need a function to get exception from the ErrorResponse class

### ISSUE THREAD

**Issue by raju-cimpress** [commercetools/commercetools-php-sdk#601]
Commercetools\Core\Response\ErrorResponse class constructor is accepting first parameter as \Exception and storing to $exception.
However neither this class nor the parent class have function to return the private $exeception
I have a scenario where I want utilize the ApiErrorException class passed to ErrorResponse by Client to get details. Also if this exception cannot be utilized than why it is stored in private variable.

**Comment by jenschude** [comment]
Thats a good question 😄 

We will add a getter to the response
