### ISSUE TITLE
HighPrecisionMoney setPreciseAmount function accepting parameter as integer which can accept max amount of 2147483647 only

### ISSUE THREAD

**Issue by raju-cimpress** [commercetools/commercetools-php-sdk#681]
**Describe the bug**
HighPrecisionMoney setPreciseAmount function accepting parameter as integer which can accept max amount of 2147483647 only

**To Reproduce**
Try setting precise amount as 9147483647
        $newAmount = 9147483647;
        $highPrecisionMoney = HighPrecisionMoney::of()
            ->setType("highPrecision")
            ->setCurrencyCode("EUR")
            ->setPreciseAmount($newAmount)
            ->setFractionDigits(9);

**Expected behavior**
setPreciseAmount argument data type should be string

**Screenshots/Code snippet**
Refer above

**Stack information (please complete the following information):**
 - PHP: 7.4
 - SDK: v2.16

**Comment by jenschude** [comment]
It's a limitation of the language itself as integers are dependent on the build 32 vs 64bit. Running on a 64bit build it would allow values up to 9 * 10^18 which should suffice. Also it can't be converted to a string as it would be incorrectly serialized to json
